from flask import Flask, request, send_from_directory, Response, json
import apiai

# Client Access Token for accessing our API AI Bot
CLIENT_ACCESS_TOKEN = 'e7b89d308bc5412a9beb266c97297604'
ai = apiai.ApiAI(CLIENT_ACCESS_TOKEN)

app = Flask(__name__)

@app.route("/")
def hello():
    return app.send_static_file('index.html')

@app.route("/message/<incomingMsg>")
def msg(incomingMsg):
	return parse_natural_text(incomingMsg);

@app.route("/script.js")
def script():
	return app.send_static_file('script.js')

@app.route("/style.css")
def style():
	return app.send_static_file('style.css')

# Takes a string of natural language text, passes it to ApiAI, returns a 
# response generated by an ApiAI bot.
def parse_natural_text(user_text):
    
    # Sending a text query to our bot with text sent by the user. 
    request = ai.text_request()
    request.query = user_text

    # Receiving the response.
    response = json.loads(request.getresponse().read().decode('utf-8'))
    responseStatus = response['status']['code']
    if (responseStatus == 200):
        # Sending the textual response of the bot.
        return (response['result']['fulfillment']['speech'])

    else:
        return ("Sorry, I couldn't understand that question")

    # NOTE:
    # At the moment, all messages sent to ApiAI cannot be differentiated,
    # they are processed as a single conversation regardless of concurrent 
    # conversations. We need to perhaps peg a session id (ApiAI) to a recipient
    # id (Messenger) to fix this.

    # request.session_id = "<SESSION ID, UNIQUE FOR EACH USER>"